In [39]:
import h5py
import pandas as pd
import numpy as np

In [66]:
filename = 'SPY_20100104.h5'
f = h5py.File(filename, 'r')

In [67]:
list(f.keys())

['df']

In [68]:
list(f['df'])

['_i_table', 'meta', 'table']

In [40]:
data = (f['df']['table'][:])

In [144]:
data.reshape(-1,1)[1:100][0][0]

(1, [5], [0], [3], [0], [1262578133188000000], [ 112.25], [1000,    0], [209], [14933188000000])

In [142]:
list(((data.reshape(-1,1))[1:100][5][0]))

[6,
 array([5], dtype=int8),
 array([0], dtype=int8),
 array([3], dtype=int8),
 array([0], dtype=int8),
 array([1262578511818000000], dtype=int64),
 array([ 112.23000336], dtype=float32),
 array([1750,    0]),
 array([216], dtype=int64),
 array([15311818000000], dtype=int64)]